### ISSUE TITLE
Concatinate a functions and strings?

### ISSUE THREAD

**Issue by se5a** [ncalc/ncalc#15]
I'm trying two write an expressions which outputs a string, with an input of both a string and a function ie:
`Expression e = new Expression("'The result of this is: ' Pow(3,2");`
Is there a way to do this?
Do I need to write a custom function to handle it.

**Comment by expeehaa** [comment]
I think doing this is a bad style because the Expression class is there to evaluate an expression, nothing more and nothing less. What you are going to do with the result shouldn't matter for it.

I would suggest that you evaluate your expression first and put that into your string, for example using string interpolation.

**Comment by se5a** [comment]
I'm using it as formula in mod data for a game. 
most of the formula fields are just for data and numeric return is fine. 
however I have one case where I want to display a string (as set in this particular field of the mod data) but also enable it to display a value as well. 

I guess I'll have to look at writing a custom function to handle it.
