### ISSUE TITLE
Breaking change in string concatenation handing between v5.0.0 and v5.2.3. 

### ISSUE THREAD

**Issue by jbrewer-cohr** [ncalc/ncalc#320]
String concatenation / parsing no longer gives the same results. This appears to have changed/broken in v5.1.0

Evaluating the expression: "'10' + 'mA - ' + (10 + 20) + 'mA'"
In versions prior to 5.1.0 yields: "10mA - 30mA"

In version 5.1.0 and later:
With ExpressionOptions.StringConcat yields: "10mA - 1020mA"
Without ExpressionOptions.StringConcat yields:  System.FormatException - Input string was not in a correct format.

There does not appear to be a way without changing the input to get the prior expected result.
Please consider either changing the behavior to give the prior result by default or adding a new option.

**Comment by alexwarren** [comment]
Just wanted to add my +1 to this, as it's affecting a project I'm working on too. It seems related to #276.

I wonder if the root of the problem is NCalc trying to parse strings and chars as numbers, which is not always desirable. It seems the new `ExpressionOptions.StringConcat` was designed to bypass this, but unfortunately it's a blunt tool, as turning it on means the _integer_ expression `1 + 2` is now evaluated as `"12"`.

For my project I need to _all_ of these test cases to pass (they are the `ShouldHandleStringConcatenation` ones with the `1 + 2` case added to the end of the list):

```
[InlineData("'to' + 'to'", "toto")]
[InlineData("'one' + 2", "one2")]
[InlineData("2 + 'one'", "2one")]
[InlineData("'1' + '2'", "12")]
[InlineData("1 + 2", 3)]
```

As it currently stands, with `ExpressionOptions.StringConcat` enabled, the final new test case does not pass. With `ExpressionOptions.StringConcat`, all test cases which are a mixture of strings and numbers do not pass.

**Comment by alexwarren** [comment]
I've submitted a PR #321 which implements the behaviour that I think is desirable here (for mine and @jbrewer-cohr 's purposes anyway), without introducing breaking changes.

**Comment by gumbarros** [comment]
Hey guys, sorry for the late response, I was at vacation. Thanks for the contribution @alexwarren.
