### ISSUE TITLE
Null Dereference discovered

### ISSUE THREAD

**Issue by mleppala** [ncalc/ncalc#57]
This project is really handy to use and while a static code analysis scan on NCalc shows a really clean codebase, however, it did contain two high rated issues. The two issues fell under Null Dereference category for NCalcParser.cs. 

**Note**: The NCalc project I scanned was an older version (not sure which version as I inherited this project) but I did replace the two line with the same line in v3.5.0 and the Null Dereference is still present. The code line below is the code from v3.5.0.

1. Line 2449 (v3.5.0: 2566):
```
retval.value = new Function((identifier36!=null?((NCalcParser.identifier_return)identifier36).value:default(Identifier)), ((arguments37!=null?((NCalcParser.arguments_return)arguments37).value:default(List<LogicalExpression>))).ToArray()); 
```
Null Dereference coming from `((arguments37!=null?((NCalcParser.arguments_return)arguments37).value:default(List<LogicalExpression>))).ToArray()`. 

If `arguments37` or `(NCalcParser.arguments_return)arguments37).value` is null a NullReferenceException will be called since cannot convert null to an array.

2. Line 2786 (v3.5.0 2887) contains two Null Dereferences
```
retval.value = new Identifier((NAME45!=null?NAME45.Text:default(string)).Substring(1, (NAME45!=null?NAME45.Text:default(string)).Length-2));
```
a. Null Dereference coming from `(NAME45!=null?NAME45.Text:default(string)).SubString(...)` 
If `NAME45` or `NAME45.Text` is null a NullReferenceException will be called since cannot call SubString on null.
b.  `NAME45!=null?NAME45.Text:default(string)).Length-2)`

If `NAME45` or `NAME45.Text` is null a NullReferenceException will be called since cannot call Length on null.

I hope that you would be able resolve this issue to ensure the functionality of your code does not stop unexpectedly.

ML

**Comment by petli** [comment]
Thanks @mleppala for reporting this. This is generated code, which is why it looks odd and I don't know why they have this construction with `default(Identifier)` etc. Those branches can never be triggered since the underlying grammar guarantees that these lines only run if there's a successful parse. Hence `identifier36`, `arguments37` and `NAME45` will never be null, and this should be considered a false positive from the scanning tool.

Any fix would require a fix to the ANTLR3 tool that generated the code. I don't want to modify generated files by hand, since those changes would be lost next time the grammar is changed and the files generated.

**Comment by mleppala** [comment]
Thanks for the update.
