### ISSUE TITLE
2sqrt(2) results in an error

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [ncalc/ncalc#62]
it's supposed to be equal to 2*sqrt(2)

**Comment by petli** [comment]
Sorry @H-A-M-G-E-R , ncalc doesn't support that shorthand syntax, you must include explicit multiplication operators.

**Comment by H-A-M-G-E-R** [comment]
implement this now

**Comment by petli** [comment]
It is not a simple fix, as it would require a fiddly change to the grammar of the expression parser and I'm not sure it would be possible to do it in a consistent way since ncalc supports arbitrary symbols.  E.g., `foo(2+3)` could either mean invoking the function `foo` with the argument 6, or multiply `foo` by 6.
